version: "3.7"
services:

  flask_app:
    build: './flask_app'
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    volumes:
      - Datavolume:/flask_app/files
      - Datavolume:/flask_app/templates

  rabbit:
    build: './rabbitmq'
    restart: unless-stopped
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"

  ml_worker:
    build: './ml_worker'
    restart: unless-stopped
    user: nobody
    depends_on:
      - rabbit
      - flask_app
    volumes:
      - Datavolume:/flask_app/files
      - Datavolume:/flask_app/templates

volumes:
  Datavolume:
